class RailCountryCodes(object):
    country_names = {
        "69": "Eritrea",
        "30": "North Korea",
        "61": "South Korea",
        "27": "Kazakhstan",
        "98": "Lebanon",
        "24": "Lithuania",
        "82": "Luxembourg",
        "25": "Latvia",
        "93": "Morocco",
        "23": "Moldova",
        "62": "Montenegro",
        "65": "Macedonia",
        "31": "Mongolia",
        "84": "Netherlands",
        "76": "Norway",
        "51": "Poland",
        "94": "Portugal",
        "53": "Romania",
        "72": "Serbia",
        "20": "Russia",
        "74": "Sweden",
        "79": "Slovenia",
        "56": "Slovakia",
        "97": "Syria",
        "66": "Tajikistan",
        "67": "Turkmenistan",
        "91": "Tunisia",
        "75": "Turkey",
        "22": "Ukraine",
        "29": "Uzbekistan",
        "32": "Vietnam",
        "41": "Albania",
        "58": "Armenia",
        "81": "Austria",
        "57": "Azerbaijan",
        "50": "Bosnia and Herzegovina",
        "88": "Belgium",
        "52": "Bulgaria",
        "21": "Belarus",
        "85": "Switzerland",
        "33": "China",
        "40": "Cuba",
        "54": "Czech Republic",
        "80": "Germany",
        "86": "Denmark",
        "92": "Algeria",
        "26": "Estonia",
        "90": "Egypt",
        "71": "Spain",
        "10": "Finland",
        "87": "France",
        "70": "United Kingdom",
        "28": "Georgia",
        "73": "Greece",
        "78": "Croatia",
        "55": "Hungary",
        "60": "Ireland",
        "95": "Israel",
        "99": "Iraq",
        "96": "Iran",
        "83": "Italy",
        "42": "Japan",
        "59": "Kyrgyzstan",
        "01": "Germany",
        "02": "Germany",
        "03": "Germany",
        "04": "Germany",
        "05": "Germany",
        "06": "Germany",
        "07": "Germany",
        "08": "Germany",
        "09": "Germany"
    }
